### ISSUE TITLE
Remove input field when in single entry mode

### ISSUE THREAD

**Issue by slavafomin** [indrimuska/angular-selector#18]
Hello!

Thank you for this great module.

However, I would suggest to remove the input field when the control is in single selection mode and `create` option is disabled. That will make it look more like a classic `<select>` control.

Right now we have to hide the blinking cursor using CSS workaround.

Thank you!

**Comment by indrimuska** [comment]
Hi @slavafomin, thank you for the kind words!

This seems an interesting suggestion, could you please provide me a little plunker example showing the behavior you've just described? Maybe this can be useful even for other users :)

**Comment by indrimuska** [comment]
I'm closing this issue, feel free to open again when you have any suggestion to supply. :)
