### ISSUE TITLE
filter selected items.

### ISSUE THREAD

**Issue by valentin-dirken** [indrimuska/angular-selector#2]
Change : 
scope.open = function () {
                    scope.isOpen = true;

```
                scope.dropdownPosition();


            };
```

TO : 
scope.open = function () {
                    scope.isOpen = true;

```
                scope.dropdownPosition();
                scope.filterSelected(); // by Valentin

            };
```

like this, you can do in the controller : 
contactsAPIservice.getEmployees()
        .success(function(response)
        {  
            $scope.EmployeesSelected = [3,10,12];  // or from a service request
            $scope.Employees = response;
        });

See you ;-)

**Comment by indrimuska** [comment]
Hi @valentin88, thank you for interesting in Angular Selector.

I'm not sure I'm understanding your problem, could you provide a Plunker, or at least give me a little context of where you're seeing it?

**Comment by valentin-dirken** [comment]
I'm at work, I'm going to answer you tonight ;-) (I will edit this post)

**Comment by indrimuska** [comment]
Hi @valentin88,
Maybe you want to update your options dynamically from a remote request.

If so, you could check out these three plunkers or just take a look at the [demo site](http://indrimuska.github.io/angular-selector/):
- [Remote fetching](http://plnkr.co/edit/LsaOX3?p=preview) - server side filtering
- [Change options dynamically](http://plnkr.co/edit/G6UP4x) - dynamic change of options array
- [Initialization from remote resource](http://plnkr.co/edit/kThvpO?p=preview) - mix of the previous two examples

Let me know if I'm wrong, or some of these examples could help you.
