### ISSUE TITLE
Overriding default backspace behavior

### ISSUE THREAD

**Issue by thrilleratwork** [indrimuska/angular-selector#27]
When Angular-Selector is in single select mode, is there an option or an ability to override the default backspace behavior of removing the entire selection?  

I would like ability to press backspace and instead of clearing the selected value, have the value prepopulated in the typeahead input and filter rerun for this value.

**Comment by indrimuska** [comment]
Hi @thrilleratwork, at the moment Angular Selector doesn't have that feature, but I think it could be very useful. Would you like to contribute in making this real?
