### ISSUE TITLE
Selector filter shows selected objects as well

### ISSUE THREAD

**Issue by shrayasr** [indrimuska/angular-selector#29]
Hi, :hand:

We're facing an issue when we try to populate the selector with data received via a HTTP request. 
## Steps to reproduce
- Get possible values via a HTTP request. Throw this inside the `options` variable that angular-selector looks inside (Say A,B,C,D)
- Get the pre selected values via a HTTP request. Throw these inside the `model` variable that angular-selector looks inside. This preselects a few values from the possible values (Say A,B)
- Click on selector
## Expected result
- Selector should allow me to select from C and D. Since A and B are already selected
## Actual result
- Selector shows everything in the list on the first click (A,B,C,D) and on second click filters to C and D

---

We were able to reproduce this without a HTTP request as well. If the list is loaded on a simple button click, the same issue happens. Here's a GIF illustrating the problem: 

![](http://i.imgur.com/0Flw9QX.gif)

The code that generates this :arrow_up: problem can be found in a plunker here: http://plnkr.co/edit/qeuxv2xP6zj6r3gxmPJO?p=preview

---

Please let us know if we can help you with any other information. Thanks so much for this. It has helped us out greatly! :beers: :blush:

**Comment by indrimuska** [comment]
Hi @shrayasr, thank you for filing this and for providing a plunker. Very nicely written description! :)

This bug is due to a missing filtering of the dropdown list after every `value` update.
I will resolve this in a minute :)

**Comment by indrimuska** [comment]
This fix is now available in [v1.3.1](https://github.com/indrimuska/angular-selector/releases/tag/1.3.1).
Thank you guys for reporting this issue :)

**Comment by shrayasr** [comment]
> Hi @shrayasr, thank you for filing this and for providing a plunker. Very nicely written description! :)

You're very welcome :) 

> This bug is due to a missing filtering of the dropdown list after every value update.
> I will resolve this in a minute :)
> This fix is now available in v1.3.1.

WOW :scream: You're awesome! Thanks a ton for such a quick fix. We owe you :blush: :+1:
