### ISSUE TITLE
"model" is not cleared if items in "options" removed and options array isn't re-created.

### ISSUE THREAD

**Issue by C00per** [indrimuska/angular-selector#30]
Hi!
The Model property cleared well when I remove the item from options, and there are other properties. But it is not cleared if there was only one item in "options" and it was removed.

**Comment by indrimuska** [comment]
Hi @C00per,
I am not able to reproduce that issue, this is the [plunker](http://plnkr.co/edit/xuWVQKM5K1ERznAE5uhO?p=preview) I've just created.
Could you please provide me a valid example showing your problem?
Thanks

**Comment by C00per** [comment]
Hi @indrimuska,
Please see the [pluker](http://plnkr.co/edit/UsOCWkHVo74QyEnQjL79?p=preview).
The problem as I can see that we use `splice()` in different ways.

**Comment by C00per** [comment]
So it works only when a copy of array is created
[plunker](http://plnkr.co/edit/bcI8WCwz3hzhFHWqyy1k?p=preview)

**Comment by indrimuska** [comment]
OK, you're right, `options` array must be deeply $watched from the inside.
I'll fix it in a minute.

**Comment by indrimuska** [comment]
`$watchCollection` should work fine, let me know if you have any troubles with this issue yet. :)

**Comment by C00per** [comment]
@indrimuska, thank you! v1.3.2. works fine!
