### ISSUE TITLE
Automatically close the list of options after choosing the item in multiple mode.

### ISSUE THREAD

**Issue by C00per** [indrimuska/angular-selector#31]
Hi,
Is it possible to have the option to close the list of items by choosing the item in the "multiple" mode?

**Comment by indrimuska** [comment]
Hi @C00per, you can use the `api` property to close the selector every time the model changes (using the native `$watch` method). Have you already tried it?

**Comment by C00per** [comment]
@indrimuska, I'll give it a try. However, It seems that using the `api` property is the too complicated solution.

**Comment by indrimuska** [comment]
It's not so hard to implement, check out this plunker:
http://plnkr.co/edit/RsvH9LkSfwjq60sbMepR?p=preview

**Comment by C00per** [comment]
Great! Thank you!

**Comment by indrimuska** [comment]
You're welcome! :)

**Comment by indrimuska** [comment]
@C00per you can now use `closeAfterSelection` property.
Check out #45.
