### ISSUE TITLE
How to limited amount selected items/tags

### ISSUE THREAD

**Issue by samuelsiau** [indrimuska/angular-selector#32]
Hi there,

I really like your angular-selector. I need to limit the amount options sit inside the .selector-input. e.g 10 options. As a user can only pick 5. So all options are visible but a user would only be able to select up to 5.

**Comment by indrimuska** [comment]
Hi @samuelsiau, this feature is not implemented yet, but it could be very useful for the all users. Anyway I don't have too much spare time to perform this in the next days, but if you want to make a PR I will be happy to review it. :)

**Comment by indrimuska** [comment]
FYI this feature is now available in the latest version [1.5.0](https://github.com/indrimuska/angular-selector/releases/tag/1.5.0).
