### ISSUE TITLE
Custom directive

### ISSUE THREAD

**Issue by Seryal85** [indrimuska/angular-selector#37]
How i can to add my custom directive with access to ngModel?

**Comment by indrimuska** [comment]
Hi @Seryal85, I don't think I have totally understand your question. Can you please explain it more?

**Comment by Seryal85** [comment]
Hi, I want to make validation for select, I found that can to do by custom directive, but need to access to ngModel.

**Comment by indrimuska** [comment]
Ok, you need to validate the field. You have two ways to achieve that goal:
- wrap the selector with your own custom directive and validate the model
- fork the project and customize it using `scope.value` attribute

It depends on how you perform validation (using native Angular APIs, or some other plugin).

**Comment by Seryal85** [comment]
Thanks, I'm using ng-message, therefore I think, first way is simply

**Comment by indrimuska** [comment]
Ok, I'm going to close this issue. If you need any other help feel free to comment again! :)
