### ISSUE TITLE
Not working with ng-if

### ISSUE THREAD

**Issue by RushabhJoshi** [indrimuska/angular-selector#43]
When I use select input with ng-if attribute it won't show any options

`<select ng-if="condition" selector multi="true" model="model" options="options" label-attr="label" value-attr="id"></select>`

**Comment by indrimuska** [comment]
Hi @RushabhJoshi, you can't use `ng-if` directive with other directives that use a private scope.
You need to wrap your select inside another block like this:

``` html
<div ng-if="condition">
    <select selector ...></select>
</div>
```

**Comment by RushabhJoshi** [comment]
Still no luck, Also tried in span tag

**Comment by indrimuska** [comment]
Check out this plunker: http://plnkr.co/edit/BppzOSMEU8edgaasr3Pt?p=preview

**Comment by RushabhJoshi** [comment]
I appreciate
and this is strange atleast your example shows options (I will see whats missing in my code), but in your example change does not reflect on browser model.

anyways solved a problem with ng-show
problem with prefill data in input,

Thanks
