### ISSUE TITLE
Change event never fires

### ISSUE THREAD

**Issue by localyost3000** [indrimuska/angular-selector#46]
Assigning a function to change, the function is never called with the arguments promised.

controller.js

```
$scope.log=function(){
    console.log(arguments);
};
```

If `change="log"` it will never fire. If `change="log()"` it fires, but always with empty arguments.

**Comment by indrimuska** [comment]
Hi @swimmadude66, you're not passing through the data in your HTML. Because of how Angular evals functions you need to pass the parameters you're trying to get to your log function in the HTML, like this: 

``` html
<select ... change="log(newValue, oldValue)" ..></select>
```
