### ISSUE TITLE
nested value on property labelAttr

### ISSUE THREAD

**Issue by codeyad** [indrimuska/angular-selector#47]
hi, i would like to know a way to use nested values in the labelAttr, for esample if a have this data:

`[id:'kjj454544sa',
     profile:{name:'myname'}]`

how can i show the name value?

**Comment by indrimuska** [comment]
Hi @codeyad, at the moment there's no way to do that with Angular Selector.
It requires some little updated at the directive, if you're interested to improve this feature I will be happy to review a pull request. :)

**Comment by indrimuska** [comment]
FYI v1.3.12 supports nested objects.

**Comment by indrimuska** [comment]
This plunker shows the behavior you needed.
http://plnkr.co/edit/EzzQZUxfsSbi8yThcOeG?p=preview
