### ISSUE TITLE
Original select element should replicate input status classes

### ISSUE THREAD

**Issue by danbouckley** [indrimuska/angular-selector#49]
I'm trying to implement form validation based on whether inputs have been interacted with. ie/ If a form input is required, and it already has currently value, removing that value should trigger an error message.

In angular-selector, the label element contains all styling, but the input containing the form validity / interaction classes (dirty, pristine etc) is too far down the DOM tree to apply any styling to this parent label. 

It would be great if these classes were replicated on the original select element, as then sibling selectors could be leveraged to style the label. eg:

``` css
select.ng-dirty + label {
  // Error Classes`
}
```

**Comment by indrimuska** [comment]
Hi @danbouckley, as you're not the only one to request such kind of feature, I decided to add standard model controller properties behavior to the hidden select in the template. 

It could also be useful for #13, #37, #48.

**Comment by indrimuska** [comment]
This is now available in the latest release: [v1.3.14](https://github.com/indrimuska/angular-selector/releases/1.3.14).

This plunker shows the behavior:
http://plnkr.co/edit/P6vB8jVhFj8h1WgDWZtr?p=preview

**Comment by danbouckley** [comment]
Thanks for the update, it's very appreciated! Thanks.

**Comment by danbouckley** [comment]
Sorry to try and re-open this issue, but unfortunately it's not working 100% as intended. The select element is getting both ng-pristine and ng-touched when a value has been removed from the selector. (This is available in your plunker)

**Comment by indrimuska** [comment]
Well, if I remove an item form the selector (or I just click-in and click-out the selector) I get `$pristine` and `$touched` to a truthy value. Do you think that after removing a value `$pristine` should be `false`?

**Comment by danbouckley** [comment]
This is correct, $pristine should be set to false and $touched should be true. Would it also be possible to set the $dirty property as well? ie/ If we have selected a new value, or entered text into the input

This would be a huge help!

**Comment by indrimuska** [comment]
Ok, let's resolve this!

**Comment by indrimuska** [comment]
Check out [v1.3.16](https://github.com/indrimuska/angular-selector/releases/1.3.16), this should solve your problems. Let me know if it works as expected.
