### ISSUE TITLE
Input width calculation is broken

### ISSUE THREAD

**Issue by sc8696** [indrimuska/angular-selector#5]
shadow.width is not a function - line 332

Also occurs on the demo pages

Chrome 46

**Comment by indrimuska** [comment]
Hi @sc8696,
Thank you for reporting this issue, this is due to a bug in the last commit.
Going to fix it asap.

**Comment by indrimuska** [comment]
Check out the new [release `0.6.3`](https://github.com/indrimuska/angular-selector/releases/tag/0.6.3).
