### ISSUE TITLE
Can we use angular filter with list specified in options attribute

### ISSUE THREAD

**Issue by kanikagupta13** [indrimuska/angular-selector#51]
Hi,

In angular, for lists there are various filters which can be applied to the list in html. One example of it is orderBy which sorts the list and as a result we don't have to apply this filter in the backend code.

Is there any way to include the angular filters or custom filters written in options of angular selector?

**Comment by indrimuska** [comment]
Nope, there's no way to apply angular's filters, you can just create a kind of workaround like this: http://plnkr.co/edit/FtPBzwexMN4EhW4QqxKp?p=preview

**Comment by kanikagupta13** [comment]
hi @indrimuska . Thank you for the workaround. But it doesn't completely solve the issue with my application. Is there any future scope of handling these filters within options?

**Comment by indrimuska** [comment]
Yes, of course. I don't have the time to implement it now due to my busy schedule, but I will appreciate any PR or help from anyone! :)
Let's move this thread to #25.

**Comment by kanikagupta13** [comment]
Ok. Thank you. :)
