### ISSUE TITLE
Getting Selected Value

### ISSUE THREAD

**Issue by sajeeshe** [indrimuska/angular-selector#52]
Hi,
I am trying to use this plugin. Its working nice but one issue is when I post the form I get object instead of the selected value. I tried my best but no luck. Can you help me to resolve this please ?

My major problem is I have to use this in a ng-repeat loop.

**Comment by sajeeshe** [comment]
this is how I get in my php file

[frmMerchant] => object:2807
    [frmVenue] => object:2815

**Comment by indrimuska** [comment]
Hi @sajeeshe, have you set the `value-attr` property?
https://github.com/indrimuska/angular-selector#options

**Comment by sajeeshe** [comment]
Yes but still getting the same

**Comment by indrimuska** [comment]
Ok, could you please provide a plunker or a working example showing that?

**Comment by indrimuska** [comment]
I'm going to close this issue, feel free to open again if you still find any problems. :)
