### ISSUE TITLE
Issue with JSON Object and arrays

### ISSUE THREAD

**Issue by vivek-mdrift-personal** [indrimuska/angular-selector#6]
Dear Indri Muska,

I was trying with your API example as given below....
$scope.remoteConfig = {
            url: "http://services.groupkt.com/country/search",
            transformResponse: function (data) {
                console.log(typeof data);
                // var str = data;
                // var json = JSON.stringify(eval("{"+"tags:" + str + "}"));  
                // var myJsonString = JSON.stringify(yourArray);
                // var catcher = JSON.stringify(data);  
                // var catcher = JSON.stringify({data});
                var catcher = {
                  'tags': JSON.parse(data)
                };
                console.log(typeof catcher);  
                var countries = angular.fromJson(data).RestResponse.result;
                return countries.map(function (country) {
                    return {
                        name: country.name,
                        code: country.alpha2_code
                    };
                });
            }
        };

However, I could not maniputate the array with catcher, which is a JSON object converted from an JSON array.
Is it necessary that we need to convert the JSON array to JSON Object?
The code pasted above is giving me errors...

Thanks.

Regards,
Vivek Elayidom

**Comment by indrimuska** [comment]
Hi @mdrift-central,
I don't understand why you're saying that is necessary to convert the JSON array to a JSON object, which object/array are you talking about? I can't see any error with the code you posted.

However, if you want to manipulate the result array data with any of your functions (catcher) you simply have to manipulate the parsed data from a valid JSON string:

``` javascript
transformResponse: function (string) {
  // parse JSON string -- similar to JSON.parse
  var myData = angular.fromJson(data);
  // manipulate your data
  var result = myData.RestResponse.result;
  var countries = result.map(function (country) {
    return { name: country.name, code: country.alpha2_code };
  });
  // apply other functions
  // ...
  // return countries array
  return countries;
}
```

Let me know if this could help you. :)

**Comment by vivek-mdrift-personal** [comment]
Thanks Indri Muska,

Your suggestion helped me a lot... Thanks and keep up the good work...
So far, I found your library the best for tagging..

All the very best.

Regards,
Vivek

**Comment by vivek-mdrift-personal** [comment]
Also, how do I call multiple RemoteConfig functions? Any suggestions?
I mean - other than separate controllers...

**Comment by indrimuska** [comment]
Glad to see you've solved this issue. :smile: 

With "multiple RemoteConfig functions", do you mean a kind of dynamic transformation callback for your ajax responses? If so, remember that the `remoteConfig` property is the same object passed to the native Angular `$http` service ([docs here](https://docs.angularjs.org/api/ng/service/$http#usage)), so you can use any valid options the service have.
