### ISSUE TITLE
Focus on load?

### ISSUE THREAD

**Issue by stephanebruckert** [indrimuska/angular-selector#65]
Hello,

I would like to do a `focus()` on `api="countriesAPI"` on page initialization.
How would I do that?

Thanks!

**Comment by indrimuska** [comment]
Hi @stephanebruckert, assuming that you are using a similar piece of code to the one in the demo page, you just need to add this other piece to your controller:

``` javascript
$scope.$watch('countriesAPI', function (api) {
    api.focus();
});
```

Hope this could help you!
