### ISSUE TITLE
Always leave dropdown list open

### ISSUE THREAD

**Issue by stephanebruckert** [indrimuska/angular-selector#67]
Hi,

I would like to keep the dropdown open all the time.

I'm already [adding the focus on load](https://github.com/indrimuska/angular-selector/issues/65), and I added a directive to prevent the dropdown list from closing when the selector looses focus.

```
.directive('input', function() {
  return {
    link: function (scope, element, attrs) {
      element.bind('blur', function (e) {
        scope.myAPI.focus();
      });
    }
  };
});
```

@indrimuska, would you be happy to see a PR that incorporates that feature inside angular-selector?

Thanks

**Comment by indrimuska** [comment]
Thank you @stephanebruckert for proposing this!
I think that this is an application level feature, what if I have about 10 selector in the same page? I don't want all of them to open at startup at the same time, so it's better to let users choose what to do in this case.

Anyway, thank you for spending your time in this project 👍
