### ISSUE TITLE
Remote search issues

### ISSUE THREAD

**Issue by matt212** [indrimuska/angular-selector#69]
Hi, 
my issues is  my search api url is /colum/words not search?colum=words .
Could you please provide pointers wherein i can configure this plugin for /colum/words

**Comment by indrimuska** [comment]
Hi @matt212,

You can simply set a Promise object as `remote` property and build your own url.

```html
<select selector remote="remote(search)" ... ></select>
````
```javascript
$scope.remote = function (search) {
    return $http({ url: '/colum/' + search });
};
```

Note:  `$http` service already returns a promise, so you don't need to wrap it yourself.

**Comment by matt212** [comment]
Hi, 
i wanted to format the response from $http which involves promise when i use one i am getting this error 
![promise issue](https://cloud.githubusercontent.com/assets/1698139/21312124/929e006a-c610-11e6-8fff-3db0a73c1f49.png)
