### ISSUE TITLE
Wrong parameters' name

### ISSUE THREAD

**Issue by mbustosp** [indrimuska/angular-selector#7]
Hi there, I was using your selector and I found that some of the parameters displayed on the documentation are wrong (i.e. groupAttr should be group-attr). I don't know how many of them have the same correction. 

Have a nice day!
BTW: Excellent job!

**Comment by indrimuska** [comment]
Hi @NorteSur, sorry for the late response.
The documentation illustrates every variable in `camelCase` naming system, but when you use them as html attribute you need to use `hyphen-case` naming system.
Thank you for the nice words :smile:
