### ISSUE TITLE
CSS broken when I will select an option

### ISSUE THREAD

**Issue by Iazzetta** [indrimuska/angular-selector#76]
I have many selectors in my form. I using bootstrap to grid them.
When I click to select some option, the angular-selector broken my CSS.

![m4ejwyh](https://cloud.githubusercontent.com/assets/10570792/22941542/fc889b64-f2cc-11e6-96c3-8d90ef29e836.png)

**Comment by Iazzetta** [comment]
To fix this in my case, I set position absolute in **.selector-container** and form-group **margin-bottom** to 50px.

**Comment by indrimuska** [comment]
Hi @lazzetta, your issue should be solved using [Bootstrap's responsive grid reset utilities](http://getbootstrap.com/css/#grid-responsive-resets).
Your solution is still affected by this issue if you increase the height of one grid cell element.

**Comment by Iazzetta** [comment]
hm.. I try use grid reset but not work. But my poor solutions resolve my problem haha
thanks
