### ISSUE TITLE
Demo page is broken

### ISSUE THREAD

**Issue by stevenvegt** [indrimuska/angular-selector#8]
The demo page is broken :(

Currently the rawgit resources return a 404. But, if you prepend them with cdn, it works.

This is expected, according to rawgit.com:

> If excessive traffic continues after throttling and blacklisting, RawGit may display an error message to users on your site to try to get your attention.

**Comment by indrimuska** [comment]
Ouch! ok @stevenvegt, thank you for reporting this! :+1:

**Comment by indrimuska** [comment]
FYI it has been changed from `rawgit.com` to `cdn.rawgit.com`.
Thank you again!

**Comment by stevenvegt** [comment]
Wow, thats fast! :smile:
