### ISSUE TITLE
Feature request: ngChange alike attribute

### ISSUE THREAD

**Issue by stevenvegt** [indrimuska/angular-selector#9]
When someone changes the selection, I need to do some work. Currently I've implemented this by a watch on the model, but this is not very elegant. Most angular input directives now support ngChange to prevent this expansive method. Do you think angular-selector will benefit from such a callback method?

Thanks for this nice component!

**Comment by indrimuska** [comment]
Mmhh interesting point, I think it could be an easy-to-implement feature request if this will help someone. I also think that Angular Selector needs some little optimizations but I don't have so much spare time to do that. Any PR will be accepted! :smile:

Anyway I will look into this in the next few days. :)

**Comment by indrimuska** [comment]
Hi @stevenvegt,
With the latest release you can have your onChange callback by providing `change` attribute to your elements like this:

``` html
<select selector
        model="browser"
        options="browsers"
        label-attr="name"
        change="myCallback(newValue, oldValue)"></select>
```

Hope this could help you! :)

**Comment by stevenvegt** [comment]
That's awesome! Thanks :+1:
